output "certificate_arn" {
  description = "ARN of the ACM certificate"
  value       = aws_acm_certificate.this.arn
}


output "certificate_id" {
  description = "ID of the ACM certificate"
  value       = aws_acm_certificate.this.id
}


output "domain_name" {
  description = "Primary domain name"
  value       = aws_acm_certificate.this.domain_name
}


output "status" {
  description = "Current ACM certificate status"
  value       = aws_acm_certificate.this.status
}


output "certificate_status" {
  description = "Current ACM certificate status"
  value       = aws_acm_certificate.this.status
}


output "validation_method" {
  description = "Certificate validation method"
  value       = aws_acm_certificate.this.validation_method
}


output "validation_records" {
  description = "DNS validation records generated by ACM"
  value = [
    for dvo in aws_acm_certificate.this.domain_validation_options : {
      domain_name = dvo.domain_name
      type        = dvo.resource_record_type
      name        = dvo.resource_record_name
      value       = dvo.resource_record_value
    }
  ]
}


output "validation_record_names" {
  description = "DNS validation CNAME record names"
  value = [
    for dvo in aws_acm_certificate.this.domain_validation_options :
    dvo.resource_record_name
  ]
}


output "validation_record_values" {
  description = "DNS validation CNAME record values"
  value = [
    for dvo in aws_acm_certificate.this.domain_validation_options :
    dvo.resource_record_value
  ]
}


output "validation_record_types" {
  description = "DNS validation record types"
  value = [
    for dvo in aws_acm_certificate.this.domain_validation_options :
    dvo.resource_record_type
  ]
}
